// One Müller-Brockmann design system for all three tools: white paper, near-black
// ink, one Swiss-red accent, mono labels, big numerals.
export const CSS = [
  '#igs-root,#igs-root *{box-sizing:border-box;margin:0;padding:0;}',
  '#igs-root{position:fixed;inset:0;z-index:2147483647;background:#fff;color:#111;',
  'font-family:Inter,-apple-system,BlinkMacSystemFont,"Helvetica Neue",Helvetica,Arial,sans-serif;',
  'font-size:15px;line-height:1.5;overflow:auto;-webkit-font-smoothing:antialiased;',
  '--accent:#e4002b;--mut:#6b6b6b;--line:#111;--hair:#e3e3e3;--ok:#0a7d28;--blue:#0a558c;',
  '--mono:ui-monospace,"SF Mono",Menlo,Consolas,"Liberation Mono",monospace;}',
  '#igs-root .wrap{max-width:1180px;margin:0 auto;padding:0 32px 110px;}',
  // top bar + nav
  '#igs-root .top{position:sticky;top:0;z-index:6;background:#fff;border-bottom:2px solid var(--line);',
  'display:flex;align-items:center;gap:18px;padding:16px 0;margin-bottom:8px;flex-wrap:wrap;}',
  '#igs-root .brand{font-family:var(--mono);font-size:11px;letter-spacing:.18em;text-transform:uppercase;}',
  '#igs-root .brand b{display:block;font-family:Inter,sans-serif;font-size:21px;letter-spacing:-.02em;font-weight:800;text-transform:none;}',
  '#igs-root .nav{display:flex;gap:0;border:2px solid var(--line);}',
  '#igs-root .nav button{border:none;border-right:2px solid var(--line);background:#fff;color:#111;min-height:42px;padding:0 18px;',
  'font-family:var(--mono);font-size:12px;letter-spacing:.06em;text-transform:uppercase;font-weight:600;}',
  '#igs-root .nav button:last-child{border-right:none;}',
  '#igs-root .nav button.on{background:var(--accent);color:#fff;}',
  '#igs-root .nav button:hover:not(.on){background:#111;color:#fff;}',
  '#igs-root .spacer{flex:1;}',
  '#igs-root .who{font-family:var(--mono);font-size:11px;color:var(--mut);text-align:right;line-height:1.4;}',
  // buttons (≥44px targets, AA contrast)
  '#igs-root button{font:inherit;cursor:pointer;border:2px solid var(--line);background:#fff;color:#111;',
  'min-height:44px;padding:0 16px;font-weight:600;letter-spacing:.01em;transition:background .12s,color .12s;}',
  '#igs-root button:hover{background:#111;color:#fff;}',
  '#igs-root button.primary{background:var(--accent);border-color:var(--accent);color:#fff;}',
  '#igs-root button.primary:hover{background:#b80023;border-color:#b80023;}',
  '#igs-root button.ghost{border-color:var(--hair);min-height:38px;padding:0 12px;}',
  '#igs-root button.danger{border-color:var(--accent);color:var(--accent);}',
  '#igs-root button.danger:hover{background:var(--accent);color:#fff;}',
  '#igs-root button:disabled{opacity:.4;cursor:not-allowed;}',
  '#igs-root .iconbtn{min-height:44px;min-width:44px;padding:0;font-size:20px;line-height:1;}',
  // kicker + sections
  '#igs-root .kicker{font-family:var(--mono);font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:var(--mut);margin:34px 0 12px;}',
  '#igs-root .kicker .accent{color:var(--accent);}',
  '#igs-root .note{font-family:var(--mono);font-size:12px;color:var(--mut);margin:14px 0;}',
  '#igs-root .warn{border-left:3px solid var(--accent);background:#fff5f6;padding:12px 14px;font-size:13px;margin:14px 0;}',
  // metric/stat grid (big numerals)
  '#igs-root .metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;background:var(--hair);border:1px solid var(--hair);}',
  '#igs-root .metric{background:#fff;padding:18px 16px 16px;min-height:104px;}',
  '#igs-root .metric .v{font-size:38px;font-weight:800;letter-spacing:-.03em;line-height:1;font-variant-numeric:tabular-nums;}',
  '#igs-root .metric .l{font-family:var(--mono);font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--mut);margin-top:10px;}',
  '#igs-root .metric .d{font-family:var(--mono);font-size:12px;margin-top:6px;font-variant-numeric:tabular-nums;}',
  '#igs-root .metric .d.up{color:#111;} #igs-root .metric .d.down{color:var(--accent);font-weight:700;}',
  // chart
  '#igs-root .chartbox{border:1px solid var(--hair);padding:20px 20px 12px;}',
  '#igs-root .chartbox svg{display:block;width:100%;height:200px;}',
  '#igs-root .legend{font-family:var(--mono);font-size:11px;color:var(--mut);display:flex;gap:20px;margin-top:8px;}',
  '#igs-root .legend i{display:inline-block;width:16px;height:0;border-top:3px solid;vertical-align:middle;margin-right:6px;}',
  // tabs
  '#igs-root .tabs{display:flex;flex-wrap:wrap;gap:0;border-bottom:2px solid var(--line);margin:8px 0 0;}',
  '#igs-root .tab{border:none;border-bottom:3px solid transparent;background:none;min-height:46px;padding:0 16px;',
  'font-family:var(--mono);font-size:12px;letter-spacing:.06em;text-transform:uppercase;color:var(--mut);}',
  '#igs-root .tab:hover{background:none;color:#111;}',
  '#igs-root .tab.on{color:#111;border-bottom-color:var(--accent);font-weight:700;}',
  '#igs-root .tab .n{font-weight:800;margin-left:6px;color:#111;}',
  // toolbar + search + filters
  '#igs-root .toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:10px;margin:18px 0 10px;}',
  '#igs-root .toolbar h3{font-size:13px;font-family:var(--mono);text-transform:uppercase;letter-spacing:.08em;color:var(--mut);font-weight:600;}',
  '#igs-root input.search,#igs-root select,#igs-root input[type=number]{font:inherit;min-height:40px;border:2px solid var(--line);padding:0 10px;background:#fff;}',
  '#igs-root input.search{flex:1;max-width:320px;}',
  '#igs-root input.search:focus,#igs-root select:focus{outline:2px solid var(--accent);outline-offset:1px;}',
  '#igs-root .chips{display:flex;flex-wrap:wrap;gap:8px;margin:6px 0 12px;}',
  '#igs-root .chip{font-family:var(--mono);font-size:11px;letter-spacing:.04em;text-transform:uppercase;border:2px solid var(--hair);background:#fff;color:var(--mut);min-height:34px;padding:0 10px;}',
  '#igs-root .chip.on{border-color:var(--accent);color:#fff;background:var(--accent);}',
  // list rows
  '#igs-root .rows{border-top:1px solid var(--hair);}',
  '#igs-root .row{display:flex;align-items:center;gap:14px;padding:10px 4px;border-bottom:1px solid var(--hair);}',
  '#igs-root .row.q-done{opacity:.5;}',
  '#igs-root .av{width:44px;height:44px;border-radius:50%;flex:none;background:#f0f0f0;object-fit:cover;',
  'display:flex;align-items:center;justify-content:center;font-weight:700;color:#999;font-size:16px;}',
  '#igs-root .row .meta{min-width:0;flex:1;}',
  '#igs-root .row .u{font-weight:600;}',
  '#igs-root .row .u a{color:#111;text-decoration:none;}',
  '#igs-root .row .u a:hover{text-decoration:underline;text-decoration-color:var(--accent);}',
  '#igs-root .row .fn{color:var(--mut);font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
  '#igs-root .row .when{font-family:var(--mono);font-size:11px;color:var(--mut);white-space:nowrap;}',
  '#igs-root .badge{font-family:var(--mono);font-size:10px;letter-spacing:.06em;text-transform:uppercase;border:1px solid var(--hair);padding:3px 6px;color:var(--mut);white-space:nowrap;}',
  '#igs-root .badge.v{border-color:#111;color:#111;} #igs-root .badge.red{border-color:var(--accent);color:var(--accent);}',
  '#igs-root .badge.ok{border-color:var(--ok);color:var(--ok);} #igs-root .badge.blue{border-color:var(--blue);color:var(--blue);}',
  '#igs-root .empty{color:var(--mut);padding:36px 4px;font-family:var(--mono);font-size:13px;}',
  '#igs-root .more{color:var(--mut);font-family:var(--mono);font-size:12px;padding:14px 4px;}',
  // checkboxes + per-row action buttons
  '#igs-root .ck{width:22px;height:22px;flex:none;accent-color:var(--accent);cursor:pointer;}',
  '#igs-root .ckwrap{display:flex;align-items:center;justify-content:center;min-width:44px;min-height:44px;margin:-10px 0 -10px -4px;cursor:pointer;}',
  '#igs-root .actbtn{min-height:36px;padding:0 12px;border:2px solid var(--accent);background:#fff;color:var(--accent);font-size:12px;font-weight:700;white-space:nowrap;}',
  '#igs-root .actbtn:hover{background:var(--accent);color:#fff;}',
  '#igs-root .actbtn.plain{border-color:var(--line);color:#111;}',
  '#igs-root .actbtn.plain:hover{background:#111;color:#fff;}',
  '#igs-root .qbadge{font-family:var(--mono);font-size:10px;letter-spacing:.06em;text-transform:uppercase;padding:3px 7px;white-space:nowrap;border:1px solid var(--hair);color:var(--mut);}',
  '#igs-root .qbadge.pending{border-color:#111;color:#111;} #igs-root .qbadge.running{border-color:var(--accent);color:var(--accent);}',
  '#igs-root .qbadge.done{border-color:var(--ok);color:var(--ok);} #igs-root .qbadge.failed{border-color:var(--accent);color:#fff;background:var(--accent);}',
  // selection toolbar
  '#igs-root .seltool{display:flex;align-items:center;flex-wrap:wrap;gap:10px;border:2px solid var(--line);padding:10px 12px;margin:14px 0 6px;background:#fafafa;}',
  '#igs-root .seltool .sc{font-family:var(--mono);font-size:12px;color:var(--mut);}',
  '#igs-root .seltool .sc b{color:#111;font-size:14px;}',
  '#igs-root .seltool .sp{flex:1;}',
  // cards (followers module)
  '#igs-root .cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:1px;background:var(--hair);border:1px solid var(--hair);margin-top:8px;}',
  '#igs-root .card{background:#fff;padding:14px;display:flex;flex-direction:column;gap:8px;}',
  '#igs-root .card .chead{display:flex;gap:10px;align-items:center;}',
  '#igs-root .card .thumbs{display:flex;gap:4px;}',
  '#igs-root .card .thumbs img{width:33%;aspect-ratio:1;object-fit:cover;background:#f0f0f0;}',
  '#igs-root .card .hl{display:flex;gap:6px;flex-wrap:wrap;}',
  '#igs-root .card .hl span{font-family:var(--mono);font-size:10px;color:var(--mut);border:1px solid var(--hair);padding:2px 5px;}',
  '#igs-root .card .cact{display:flex;gap:6px;flex-wrap:wrap;margin-top:auto;}',
  // dropzone
  '#igs-root .drop{border:2px dashed var(--line);padding:40px 20px;text-align:center;font-family:var(--mono);font-size:13px;color:var(--mut);cursor:pointer;}',
  '#igs-root .drop.over{border-color:var(--accent);background:#fff5f6;color:#111;}',
  // queue panel (fixed bottom bar)
  '#igs-root .qpanel{position:fixed;left:0;right:0;bottom:0;z-index:15;background:#111;color:#fff;',
  'display:flex;align-items:center;gap:16px;padding:12px 24px;border-top:3px solid var(--accent);}',
  '#igs-root .qpanel .qstat{font-family:var(--mono);font-size:12px;line-height:1.45;white-space:nowrap;}',
  '#igs-root .qpanel .qstat b{font-size:15px;}',
  '#igs-root .qpanel .qbar{flex:1;height:6px;background:#333;min-width:80px;}',
  '#igs-root .qpanel .qbar i{display:block;height:100%;background:var(--accent);transition:width .4s;}',
  '#igs-root .qpanel .qnext{font-family:var(--mono);font-size:12px;color:#ccc;white-space:nowrap;}',
  '#igs-root .qpanel button{min-height:38px;padding:0 12px;border-color:#555;background:#111;color:#fff;}',
  '#igs-root .qpanel button:hover{background:#fff;color:#111;}',
  '#igs-root .qpanel button.primary{background:var(--accent);border-color:var(--accent);}',
  '#igs-root .qpanel.rl{background:#5a0011;}',
  '#igs-root select{font-family:var(--mono);}',
  // scan overlay
  '#igs-root .scan{position:fixed;inset:0;background:rgba(255,255,255,.97);z-index:20;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;}',
  '#igs-root .radar{position:relative;width:140px;height:140px;}',
  '#igs-root .radar .ring{position:absolute;inset:0;border:3px solid var(--accent);border-radius:50%;animation:igspulse 1.8s ease-out infinite;}',
  '#igs-root .radar .ring:nth-child(2){animation-delay:.6s;} #igs-root .radar .ring:nth-child(3){animation-delay:1.2s;}',
  '#igs-root .radar .sweep{position:absolute;inset:0;border-radius:50%;border-top:3px solid #111;animation:igsspin 1s linear infinite;}',
  '@keyframes igspulse{0%{transform:scale(.2);opacity:.9;}100%{transform:scale(1);opacity:0;}}',
  '@keyframes igsspin{to{transform:rotate(360deg);}}',
  '#igs-root .scan .lot{width:140px;height:140px;position:absolute;}',
  '#igs-root .scan .st{font-family:var(--mono);font-size:13px;margin-top:24px;text-align:center;}',
  '#igs-root .scan .pct{font-size:60px;font-weight:800;letter-spacing:-.04em;font-variant-numeric:tabular-nums;}',
  '#igs-root .scan .bar{width:280px;height:6px;background:var(--hair);margin-top:8px;}',
  '#igs-root .scan .bar i{display:block;height:100%;background:var(--accent);width:0;transition:width .3s;}',
  '#igs-root .igs-toast{position:fixed;left:50%;bottom:86px;transform:translateX(-50%);background:#111;color:#fff;font:600 13px Inter,sans-serif;padding:12px 18px;z-index:2147483647;border-left:3px solid var(--accent);}',
  '@media(max-width:880px){#igs-root .metrics{grid-template-columns:repeat(3,1fr);}#igs-root .wrap{padding:0 16px 110px;}}',
  '@media(max-width:520px){#igs-root .metrics{grid-template-columns:repeat(2,1fr);}}',
].join('');
